name: CI/CD for Feature Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: feast
          POSTGRES_PASSWORD: feast
          POSTGRES_DB: feast
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feast[postgres]

    - name: Wait for Postgres to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for postgres..."
          sleep 1
        done

    - name: Apply Feast feature store
      run: |
        feast apply
        feast materialize-incremental $(date +%Y-%m-%dT%H:%M:%S)

    - name: Run tests
      run: |
        pytest tests/

    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Comandi per il deploy in produzione
        echo "Deploying to production"
