name: CI/CD for Feature Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools
        python -m pip install --upgrade pip
        pip install feast[redis]

    - name: Wait for Redis to be ready
      run: |
        until redis-cli -h localhost ping; do
          echo "Waiting for redis..."
          sleep 1
        done

    - name: Apply Feast feature store
      run: |
        cd bank_customer/feature_repo
        feast apply
        feast materialize-incremental $(date +%Y-%m-%dT%H:%M:%S)

    - name: Run tests
      run: |
        pytest tests/

    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Comandi per il deploy in produzione
        echo "Deploying to production"
